export default {
 runtime: {"title": "Account containers and egress", "hint": "Create a CCGateway account and choose its proxy on the Accounts page. Proxy changes synchronize automatically. Calls never configure egress. Accounts without proxies are blocked.", "switchHint": "Proxy changes restart this account’s egress and may interrupt existing calls. Other accounts are unaffected.", "select": "Select account", "state": "Synchronization", "ready": "Applied", "pending": "Pending or failed", "retry": "Retry synchronization", "failed": "Runtime unavailable. Check the remote controller, proxy and containers.", "enable": "Enable per-account containers and external egress", "setup": "Install the remote account controller at 127.0.0.1:8787 first and use its key as the admin key. Shared containers are not automatically migrated."},
  title: 'CCGateway management', description: 'Manage local or SSH gateways, outbound proxies and Claude authorization.', readOnly: 'Your permissions allow viewing configuration only.', failed: 'Operation failed. Check the connection configuration and retry.',
  auth: { createHint: 'After saving, a dedicated container is prepared for this account and you finish the Claude authorization right here: get the authorization link, sign in to Claude in the browser, paste the code back.', preparing: 'Preparing the account container; the authorization link is available once it is ready…', unavailable: 'The account container is unavailable: make sure CCGateway has per-account containers enabled and a working Docker connection.', settings: 'Open CCGateway settings', readOnly: 'Authorizing needs the settings:manage permission.', steps: 'Steps: get the authorization link, sign in to Claude on the page that opens and approve, copy the full code shown (code#state) into the field below, then complete.', apiKeyMode: 'Authentication: API Key', oauthMode: 'Authentication: OAuth', apiKeyHint: 'Configure API Key and Base URL in the account editor. No OAuth login is required. Updating credentials recreates this account container, preserving data, and may interrupt active requests.', models: 'Models', modelsHint: 'Prefilled with the plugin preset; add or remove freely. Press Enter after a model name; an empty list allows every model.', mapping: 'Model mapping', mappingHint: 'Request model → upstream model; billing and group allowlists still use the request model.', title: 'Claude authorization and account', hint: 'Provide Messages API through Claude Code. Each container has its own authorization.', healthy: 'Service online', offline: 'Service unavailable', loggedIn: 'Authorized', loggedOut: 'Not authorized', unknown: 'Status unknown', start: 'Get authorization link', logout: 'Sign out', confirmLogout: 'Signing out prevents linked accounts from calling models. Continue?', open: 'Open Claude authorization', expires: 'Authorization link expires: {time}', code: 'Full authorization code (code#state)', complete: 'Complete authorization', expired: 'Session expired. Cancel and request a new authorization link.', name: 'Account name', connect: 'Create scheduling account', connected: 'Created account #{id}', accounts: 'Open accounts', connectHint: 'Create a managed CCGateway account with core-managed credentials. Choose groups here; accounts without groups do not participate in scheduling.', pending: 'Authorization callback completed. Refresh status to confirm.' },

    proxy: {
      title: 'CCGateway outbound proxy', description: 'Configure Claude CLI outbound connections. Only HTTP / HTTPS proxies are supported; the official CLI does not support SOCKS.', effect: 'New requests use the saved configuration. In-flight requests keep their previous proxy; no container restart is required. The proxy must be reachable from the remote container.',
      mode: 'Proxy mode', inherit: 'Inherit container environment', direct: 'Connect directly', proxy: 'Custom proxy', url: 'Proxy URL', keep: 'Saved; leave blank to retain', support: 'HTTP / HTTPS URLs may include authentication. Saved credentials are never returned.', current: 'Saved proxy:', clear: 'Saving this mode clears the stored custom proxy URL.', revision: 'Configuration revision {revision}',
      save: 'Save outbound proxy', saved: 'Proxy configuration saved for new requests.', reload: 'Reload proxy configuration', required: 'Enter a URL when configuring a proxy for the first time.', invalid: 'Enter a valid HTTP or HTTPS proxy URL.', failed: 'Proxy operation failed. Check the connection and configuration, then retry.', show: 'Show', hide: 'Hide'
    },
    remote: {
      unconfigured: 'Not configured',
      admin_key: 'Container admin key (CCG_ADMIN_KEY)', api_key: 'Container API key (CCG_API_KEY)', keysHint: 'Use target container keys. Saved values are never returned; leave blank to retain.',
      title: 'CCGateway Docker connection', authorization: 'Built-in · Gateway authorization', description: 'Manage an existing CCGateway container locally or through SSH. This does not install Docker or deploy an image.',
      routingHint: 'SSH mode tunnels authorization and model requests to remote 127.0.0.1:8787; Docker and gateway API ports need not be public. Local mode still uses CCGATEWAY_URL. The saved CCG_API_KEY and CCG_ADMIN_KEY below must match the target container.',
      mode: 'Connection mode', local: 'Local Docker', ssh: 'Remote SSH', host: 'SSH host', port: 'SSH port', user: 'SSH user', authMode: 'SSH authentication', password: 'SSH password', privateKey: 'SSH private key', passphrase: 'Private key passphrase (optional)',
      fingerprint: 'Host key fingerprint', probe: 'Probe host fingerprint', verifyFingerprint: 'Verify this fingerprint through a trusted channel. The discovered fingerprint is not saved automatically; explicitly use it after checking.', useFingerprint: 'Use this fingerprint',
      keepSecret: 'Saved; leave blank to keep', secretsHint: 'Passwords, private keys and passphrases are never returned. Leave blank to retain saved values. Do not enter Claude authorization codes or model API keys here.', newCredentials: 'After changing the host, port or SSH user, enter the corresponding password or private key again.',
      required: 'Enter a valid SSH host, port, user and host fingerprint.', targetRequired: 'Enter an SSH host and a valid port first.',
      save: 'Save connection', saved: 'Connection configuration saved.', reload: 'Reload configuration', test: 'Test saved connection', saveFirst: 'Save the configuration before testing or managing containers.', savedOnly: 'Actions use only the saved SSH configuration. Remote actions are unavailable in local mode.',
      actions: { status: 'Container status', start: 'Start container', stop: 'Stop container', restart: 'Restart container', logs: 'View logs' },
      confirmAction: 'Run “{action}”? This may interrupt requests handled by the container.', confirm: 'Confirm action', cancel: 'Cancel', failed: 'Operation failed. Please retry.'
    },
}
