export default {
  title: 'Model prices',
  description: 'Billing expressions per model. Admin prices take precedence over plugin defaults.',
  scopeNote: 'Prices are set globally per model, whatever endpoint or account type serves the request. The expression gives the base price; the amount charged = base price × group rate multiplier.',
  new: 'New price',
  newTitle: 'New price',
  editTitle: 'Edit price · {name}',
  editTitleShort: 'Edit price',
  pluginDefaultReadonly: 'Default price provided by plugin {plugin}. It is read-only; override it to create an admin price.',
  source: {
    admin: 'Admin',
    plugin_default: 'Plugin default'
  },
  override: 'Override',
  overridden: 'Admin copy created',
  overrideNote: '"Override" copies a plugin default price into an admin price; plugin upgrades never change admin prices.',
  basic: 'Basic',
  modelPattern: 'Model',
  modelPatternHint: 'Exact name or wildcard, e.g. claude-sonnet-*',
  modeCol: 'Mode',
  summaryCol: 'Summary',
  searchPlaceholder: 'Model, note, plugin…',
  exprHash: 'Expression hash',
  viewHistory: 'View expression',
  billingMode: 'Billing mode',
  expression: 'Expression',
  view: {
    visual: 'Visual',
    source: 'Source'
  },
  mode: {
    per_request: 'Per request',
    per_token: 'Per token',
    expression: 'Expression'
  },
  modeHint: {
    per_request: 'A fixed USD price for every call (images, search, …).',
    per_token: 'USD per 1M tokens for input, output, cache read and cache writes.',
    expression: 'Context-length tiers, markup rules by header, parameter or time of day — or write the expression directly.'
  },
  perRequestPrice: 'Price per request (USD)',
  perMillion: 'Price per 1M tokens (USD)',
  vars: {
    p: 'Input',
    c: 'Output',
    cr: 'Cache read',
    cc: 'Cache write 5m',
    cc1h: 'Cache write 1h',
    flat: 'Flat fee'
  },
  unsetPlaceholder: 'free',
  cacheUnsetHint: 'Cache tokens without a price are not billed.',
  notVisual: 'This expression cannot be represented visually; edit it in source mode.',
  sourceHint: 'Rules are appended with three vertical bars, e.g. COND ? 1.5 : 1',
  generated: 'Generated expression (read-only)',
  serverGenerated: 'Expression generated by the server',
  validate: {
    title: 'Validation',
    ok: 'Compiled and smoke-tested',
    pending: 'Waiting for input…',
    fixErrors: 'Fix the validation errors first',
    warnTitle: 'Confirm high cost',
    warnConfirm: 'The server reported: {list}. Save anyway?',
    costPerMillion: 'Cost of 1M input tokens: {cost}'
  },
  trial: {
    title: 'Trial calculation',
    len: 'len (context)',
    headers: 'Request headers',
    params: 'Request parameters',
    paramsHint: 'Values are parsed as JSON when possible (1.5, true, "x"), otherwise sent as strings.',
    at: 'Time',
    group: 'Group (rate)',
    calculate: 'Calculate',
    fixFirst: 'Fix the price definition to calculate.',
    cost: 'Cost',
    tier: 'Tier',
    rules: 'Markup rules',
    breakdown: 'Breakdown',
    empty: 'Enter usage to calculate.'
  },
  items: {
    p: 'Input',
    c: 'Output',
    cr: 'Cache read',
    cc: 'Cache write 5m',
    cc1h: 'Cache write 1h',
    flat: 'Flat fee',
    other: 'Other',
    subtotal: 'Subtotal',
    rules: 'markup',
    groupRate: 'group rate'
  },
  summary: {
    perRequest: '{price} / request',
    perToken: 'in {p} · out {c} · cache read {cr} /M',
    visual: '{tiers} tier(s) · {rules} markup rule(s)',
    custom: 'Custom expression'
  },
  local: {
    noTier: 'Add at least one tier',
    tierName: 'Tier {n} needs a name',
    tierDup: 'Duplicate tier name "{name}"',
    tierMax: 'Tier "{name}" needs a max context length',
    ruleField: 'Markup rule {n} is incomplete',
    emptyExpr: 'The expression is empty'
  },
  history: {
    title: 'Expression history',
    notFound: 'No expression stored under this hash.'
  },
  visual: {
    tiers: 'Tiers (by len = full context length)',
    tiersHint: 'Tiers are checked in ascending order of their limit; the last one applies otherwise.',
    addTier: 'Tier',
    tierName: 'Tier',
    condLen: 'when len ≤',
    otherwise: 'otherwise',
    always: 'always',
    rules: 'Markup rules',
    rulesHint: 'Each matching rule multiplies the cost.',
    addRule: 'Rule',
    noRules: 'No markup rules.',
    when: 'When',
    kind: {
      header: 'Header',
      param: 'Parameter',
      time: 'Time'
    },
    op: {
      contains: 'contains',
      eq: 'equals'
    },
    headerName: 'header name',
    paramPath: 'parameter path',
    value: 'value',
    tz: 'time zone',
    hour: '{h}:00',
    multiplier: 'multiplier'
  }
}
