// Exports the <SIcon> name vocabulary to next/sdk/manifest/check/icons.json,
// which Go embeds to validate manifest `ui.menus[].icon` statically.
//
//   npm run icons:json
//
// icons.ts is pure data with no browser dependency, so node can import it
// directly (type stripping; no bundler, no DOM).
//
// The file also carries a sha256 of icons.ts itself. That hash is the whole
// point: a generated artifact nobody can tell is stale is the same silent
// failure this validation exists to kill. Go's TestEmbeddedIconsMatchTheSource
// re-hashes icons.ts and fails when it differs, so "added an icon and forgot
// to regenerate" is a red test carrying the command to run, not an icon the
// validator quietly accepts or rejects. Hashing the source rather than diffing
// the names means a comment-only edit also asks for a regeneration - the
// answer is one idempotent command, and the alternative (a second, looser
// TypeScript parser written in Go) is the thing that eventually disagrees
// with this one.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { ICON_NAMES } from '../packages/ui/src/icons.ts'

const here = dirname(fileURLToPath(import.meta.url))
/** Path of icons.ts relative to the repository root, as recorded in the JSON. */
const SOURCE_REL = 'next/web/packages/ui/src/icons.ts'
const repoRoot = resolve(here, '../../..')
const sourcePath = resolve(repoRoot, SOURCE_REL)
const outPath = resolve(here, '../../sdk/manifest/check/icons.json')

/**
 * Line endings are normalised and a leading BOM dropped before hashing, so a
 * CRLF checkout (git core.autocrlf on Windows) and an LF one agree. Keep this
 * identical to the Go side (check.hashIconSource).
 */
function sourceHash(path: string): string {
  let text = readFileSync(path, 'utf8')
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1)
  return createHash('sha256').update(text.replace(/\r\n/g, '\n'), 'utf8').digest('hex')
}

const names = [...ICON_NAMES].sort()
if (names.length === 0) throw new Error(`${SOURCE_REL} exported no icon names`)
const dupe = names.find((n, i) => i > 0 && n === names[i - 1])
if (dupe) throw new Error(`duplicate icon name ${JSON.stringify(dupe)}`)

const doc = {
  _comment: `Generated by "npm run icons:json" in next/web. Do not edit; edit ${SOURCE_REL} and regenerate.`,
  source: SOURCE_REL,
  source_sha256: sourceHash(sourcePath),
  names
}
writeFileSync(outPath, JSON.stringify(doc, null, 2) + '\n')
console.log(`wrote ${outPath} (${names.length} icon names)`)
