package e2e

import (
	"archive/zip"
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"io"
	"sort"
	"strconv"
	"testing"

	"github.com/Sub2API-Devs/sup2api/next/sdk/pkgsig"
)

// Package is an in-memory .s2plugin (path -> content).
type Package map[string][]byte

// ReadPackage unzips a .s2plugin.
func ReadPackage(t testing.TB, data []byte) Package {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		t.Fatalf("read package: %v", err)
	}
	p := Package{}
	for _, f := range zr.File {
		if f.FileInfo().IsDir() {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			t.Fatal(err)
		}
		b, _ := io.ReadAll(rc)
		rc.Close()
		p[f.Name] = b
	}
	return p
}

// Bytes zips the package (sorted paths; runtimes stay executable).
func (p Package) Bytes(t testing.TB) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	names := make([]string, 0, len(p))
	for n := range p {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		h := &zip.FileHeader{Name: n, Method: zip.Deflate}
		h.SetMode(0o644)
		if len(n) > 9 && n[:9] == "runtimes/" {
			h.SetMode(0o755)
		}
		w, err := zw.CreateHeader(h)
		if err != nil {
			t.Fatal(err)
		}
		_, _ = w.Write(p[n])
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// Manifest decodes manifest.json into a generic map.
func (p Package) Manifest(t testing.TB) map[string]any {
	t.Helper()
	var m map[string]any
	if err := json.Unmarshal(p[pkgsig.ManifestFile], &m); err != nil {
		t.Fatalf("manifest: %v", err)
	}
	return m
}

// SetManifest re-encodes manifest.json (the signature becomes invalid).
func (p Package) SetManifest(t testing.TB, m map[string]any) {
	t.Helper()
	raw, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	p[pkgsig.ManifestFile] = raw
}

// Tamper flips the last byte of path (or appends one to an empty file) without
// re-signing, so signature verification must fail.
func (p Package) Tamper(t testing.TB, path string) {
	t.Helper()
	b, ok := p[path]
	if !ok {
		t.Fatalf("tamper: %s not in package", path)
	}
	c := append([]byte(nil), b...)
	if len(c) == 0 {
		c = []byte{0}
	} else {
		c[len(c)-1] ^= 0xff
	}
	p[path] = c
}

// FirstNonManifestFile returns a stable file to tamper with.
func (p Package) FirstNonManifestFile() string {
	names := make([]string, 0, len(p))
	for n := range p {
		if n != pkgsig.ManifestFile && n != pkgsig.SignatureFile {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	if len(names) == 0 {
		return pkgsig.ManifestFile
	}
	return names[0]
}

// Sign rewrites signature.json with key.
func (p Package) Sign(t testing.TB, k *SigningKey) {
	t.Helper()
	files := map[string][]byte{}
	for n, b := range p {
		if n != pkgsig.SignatureFile {
			files[n] = b
		}
	}
	sig, err := pkgsig.Sign(files, k.Publisher, k.KeyID, k.Private)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	raw, _ := json.MarshalIndent(sig, "", "  ")
	p[pkgsig.SignatureFile] = raw
}

// SigningKey is an Ed25519 publisher key generated by a test.
type SigningKey struct {
	Publisher string
	KeyID     string
	Public    ed25519.PublicKey
	Private   ed25519.PrivateKey
}

// PublicB64 is the base64 public key as stored in publisher_keys.
func (k *SigningKey) PublicB64() string { return base64.StdEncoding.EncodeToString(k.Public) }

// NewSigningKey generates a key for publisher.
func NewSigningKey(t testing.TB, publisher, keyID string) *SigningKey {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	return &SigningKey{Publisher: publisher, KeyID: keyID, Public: pub, Private: priv}
}

func sha256hex(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}

func itoa(n int64) string { return strconv.FormatInt(n, 10) }
