package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/config"
	jwt "github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"
)

const (
	workerNATSURLSettingKey      = "worker_nats_url"
	workerNATSTTLSettingKey      = "worker_nats_credential_ttl_days"
	defaultWorkerNATSTTLDays     = 0
	maximumWorkerNATSTTLDays     = 3650
	workerNATSAuthenticationMode = "nkey_jwt_nsc"
)

type nscProfileDetails struct {
	Name string `json:"name"`
	Seed string `json:"seed"`
	Key  string `json:"id"`
}

type nscIssuerProfile struct {
	Operator *nscProfileDetails `json:"operator"`
	Account  *nscProfileDetails `json:"account"`
}

// WorkerNATSIssuer signs least-privilege Worker user JWTs with the Account
// identity generated by nsc. The NATS server receives only public Operator and
// Account JWTs; the Account seed is mounted exclusively into the control plane.
type WorkerNATSIssuer struct {
	enabled                      bool
	profileFile                  string
	controlCredentialsFile       string
	defaultWorkerURL             string
	subject                      string
	operatorID                   string
	accountID                    string
	operatorName                 string
	accountName                  string
	controlCredentialsConfigured bool
}

func NewWorkerNATSIssuer(cfg *config.Config) (*WorkerNATSIssuer, error) {
	issuer := &WorkerNATSIssuer{}
	if cfg == nil || !cfg.UsageQueue.Enabled {
		return issuer, nil
	}
	issuer.enabled = true
	issuer.profileFile = strings.TrimSpace(cfg.UsageQueue.IssuerProfileFile)
	issuer.controlCredentialsFile = strings.TrimSpace(cfg.UsageQueue.CredentialsFile)
	issuer.defaultWorkerURL = strings.TrimSpace(cfg.UsageQueue.WorkerURL)
	issuer.subject = strings.TrimSpace(cfg.UsageQueue.Subject)

	profile, err := issuer.loadProfile()
	if err != nil {
		return nil, err
	}
	issuer.operatorID = strings.TrimSpace(profile.Operator.Key)
	issuer.accountID = strings.TrimSpace(profile.Account.Key)
	issuer.operatorName = strings.TrimSpace(profile.Operator.Name)
	issuer.accountName = strings.TrimSpace(profile.Account.Name)
	controlCredentials, err := os.ReadFile(issuer.controlCredentialsFile)
	if err == nil {
		defer clear(controlCredentials)
		controlJWT, parseErr := nkeys.ParseDecoratedJWT(controlCredentials)
		if parseErr != nil {
			return nil, fmt.Errorf("parse NATS control JWT: %w", parseErr)
		}
		controlClaims, parseErr := jwt.DecodeUserClaims(controlJWT)
		if parseErr != nil {
			return nil, fmt.Errorf("decode NATS control JWT: %w", parseErr)
		}
		if controlClaims.Issuer != issuer.accountID && controlClaims.IssuerAccount != issuer.accountID {
			return nil, errors.New("NATS control credentials were not issued by the configured Workers Account")
		}
		controlPair, parseErr := nkeys.ParseDecoratedUserNKey(controlCredentials)
		if parseErr != nil {
			return nil, fmt.Errorf("parse NATS control NKey: %w", parseErr)
		}
		controlPublic, publicErr := controlPair.PublicKey()
		controlPair.Wipe()
		if publicErr != nil || controlPublic != controlClaims.Subject {
			return nil, errors.New("NATS control NKey does not match its user JWT")
		}
		issuer.controlCredentialsConfigured = true
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("inspect NATS control credentials: %w", err)
	}
	return issuer, nil
}

func (i *WorkerNATSIssuer) loadProfile() (*nscIssuerProfile, error) {
	if i == nil || strings.TrimSpace(i.profileFile) == "" {
		return nil, errors.New("nsc issuer profile is not configured")
	}
	raw, err := os.ReadFile(i.profileFile)
	if err != nil {
		return nil, fmt.Errorf("read nsc issuer profile: %w", err)
	}
	defer clear(raw)
	var profile nscIssuerProfile
	if err := json.Unmarshal(raw, &profile); err != nil {
		return nil, fmt.Errorf("decode nsc issuer profile: %w", err)
	}
	if profile.Operator == nil || !nkeys.IsValidPublicOperatorKey(strings.TrimSpace(profile.Operator.Key)) {
		return nil, errors.New("nsc issuer profile does not contain a valid Operator public key")
	}
	if profile.Account == nil || !nkeys.IsValidPublicAccountKey(strings.TrimSpace(profile.Account.Key)) {
		return nil, errors.New("nsc issuer profile does not contain a valid Account public key")
	}
	accountPair, err := nkeys.FromSeed([]byte(strings.TrimSpace(profile.Account.Seed)))
	if err != nil {
		return nil, fmt.Errorf("decode nsc Account seed: %w", err)
	}
	defer accountPair.Wipe()
	accountPublic, err := accountPair.PublicKey()
	if err != nil {
		return nil, fmt.Errorf("derive nsc Account public key: %w", err)
	}
	if accountPublic != strings.TrimSpace(profile.Account.Key) {
		return nil, errors.New("nsc Account seed does not match the configured Account public key")
	}
	return &profile, nil
}

func (i *WorkerNATSIssuer) Issue(workerID, subject string, ttlDays int) (string, string, error) {
	if i == nil || !i.enabled {
		return "", "", errors.New("NATS NKey/JWT issuer is not configured")
	}
	workerID = strings.TrimSpace(workerID)
	if workerID == "" {
		return "", "", errors.New("worker ID is required for NATS credential issuance")
	}
	if ttlDays < 0 || ttlDays > maximumWorkerNATSTTLDays {
		return "", "", fmt.Errorf("NATS credential TTL must be between 0 and %d days", maximumWorkerNATSTTLDays)
	}
	profile, err := i.loadProfile()
	if err != nil {
		return "", "", err
	}
	accountPair, err := nkeys.FromSeed([]byte(strings.TrimSpace(profile.Account.Seed)))
	if err != nil {
		return "", "", fmt.Errorf("open nsc Account signer: %w", err)
	}
	defer accountPair.Wipe()
	userPair, err := nkeys.CreateUser()
	if err != nil {
		return "", "", fmt.Errorf("generate Worker NKey: %w", err)
	}
	defer userPair.Wipe()
	userPublic, err := userPair.PublicKey()
	if err != nil {
		return "", "", fmt.Errorf("derive Worker NKey public key: %w", err)
	}
	claims := jwt.NewUserClaims(userPublic)
	claims.Name = "worker:" + workerID
	claims.Permissions.Pub.Allow.Add(subject)
	claims.Permissions.Sub.Allow.Add("_INBOX.>")
	if ttlDays > 0 {
		claims.Expires = time.Now().UTC().Add(time.Duration(ttlDays) * 24 * time.Hour).Unix()
	}
	token, err := claims.Encode(accountPair)
	if err != nil {
		return "", "", fmt.Errorf("sign Worker NATS JWT: %w", err)
	}
	seed, err := userPair.Seed()
	if err != nil {
		return "", "", fmt.Errorf("export Worker NKey seed: %w", err)
	}
	defer clear(seed)
	credentials, err := jwt.FormatUserConfig(token, seed)
	if err != nil {
		return "", "", fmt.Errorf("format Worker NATS credentials: %w", err)
	}
	return string(credentials), userPublic, nil
}

type WorkerNATSSecurityConfig struct {
	AuthenticationMode           string `json:"authentication_mode"`
	Ready                        bool   `json:"ready"`
	WorkerURL                    string `json:"worker_url"`
	Subject                      string `json:"subject"`
	CredentialTTLDays            int    `json:"credential_ttl_days"`
	OperatorID                   string `json:"operator_id"`
	OperatorName                 string `json:"operator_name"`
	AccountID                    string `json:"account_id"`
	AccountName                  string `json:"account_name"`
	IssuerConfigured             bool   `json:"issuer_configured"`
	ControlCredentialsConfigured bool   `json:"control_credentials_configured"`
}

type UpdateWorkerNATSSecurityInput struct {
	WorkerURL         string `json:"worker_url"`
	CredentialTTLDays int    `json:"credential_ttl_days"`
}

func validateWorkerNATSURL(raw string) (string, error) {
	raw = strings.TrimSpace(raw)
	parsed, err := url.Parse(raw)
	if err != nil || parsed.Host == "" {
		return "", errors.New("Worker NATS URL must be a valid URL")
	}
	if parsed.User != nil {
		return "", errors.New("Worker NATS URL must not contain credentials")
	}
	switch strings.ToLower(parsed.Scheme) {
	case "tls", "wss":
	default:
		return "", errors.New("Worker NATS URL must use tls or wss")
	}
	return parsed.String(), nil
}

func workerNATSTTLDays(raw string) int {
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || value < 0 || value > maximumWorkerNATSTTLDays {
		return defaultWorkerNATSTTLDays
	}
	return value
}

func (s *WorkerService) GetNATSSecurityConfig(ctx context.Context) (*WorkerNATSSecurityConfig, error) {
	if s == nil || s.natsIssuer == nil {
		return &WorkerNATSSecurityConfig{AuthenticationMode: workerNATSAuthenticationMode}, nil
	}
	workerURL := s.natsIssuer.defaultWorkerURL
	ttlDays := defaultWorkerNATSTTLDays
	if s.settings != nil {
		values, err := s.settings.GetMultiple(ctx, []string{workerNATSURLSettingKey, workerNATSTTLSettingKey})
		if err != nil {
			return nil, err
		}
		if value := strings.TrimSpace(values[workerNATSURLSettingKey]); value != "" {
			workerURL = value
		}
		ttlDays = workerNATSTTLDays(values[workerNATSTTLSettingKey])
	}
	_, urlErr := validateWorkerNATSURL(workerURL)
	issuerConfigured := s.natsIssuer.enabled && s.natsIssuer.accountID != ""
	return &WorkerNATSSecurityConfig{
		AuthenticationMode: workerNATSAuthenticationMode,
		Ready:              issuerConfigured && s.natsIssuer.controlCredentialsConfigured && urlErr == nil,
		WorkerURL:          workerURL, Subject: s.natsIssuer.subject, CredentialTTLDays: ttlDays,
		OperatorID: s.natsIssuer.operatorID, OperatorName: s.natsIssuer.operatorName,
		AccountID: s.natsIssuer.accountID, AccountName: s.natsIssuer.accountName,
		IssuerConfigured:             issuerConfigured,
		ControlCredentialsConfigured: s.natsIssuer.controlCredentialsConfigured,
	}, nil
}

func (s *WorkerService) UpdateNATSSecurityConfig(ctx context.Context, input UpdateWorkerNATSSecurityInput) (*WorkerNATSSecurityConfig, error) {
	if s == nil || s.settings == nil || s.natsIssuer == nil || !s.natsIssuer.enabled {
		return nil, errors.New("NATS NKey/JWT security is not configured")
	}
	workerURL, err := validateWorkerNATSURL(input.WorkerURL)
	if err != nil {
		return nil, err
	}
	if input.CredentialTTLDays < 0 || input.CredentialTTLDays > maximumWorkerNATSTTLDays {
		return nil, fmt.Errorf("NATS credential TTL must be between 0 and %d days", maximumWorkerNATSTTLDays)
	}
	if err := s.settings.SetMultiple(ctx, map[string]string{
		workerNATSURLSettingKey: workerURL,
		workerNATSTTLSettingKey: strconv.Itoa(input.CredentialTTLDays),
	}); err != nil {
		return nil, err
	}
	return s.GetNATSSecurityConfig(ctx)
}

func clear(data []byte) {
	for index := range data {
		data[index] = 0
	}
}
