// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: api/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_OPENAI      Protocol = 1
	Protocol_PROTOCOL_ANTHROPIC   Protocol = 2
	Protocol_PROTOCOL_GEMINI      Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_OPENAI",
		2: "PROTOCOL_ANTHROPIC",
		3: "PROTOCOL_GEMINI",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_OPENAI":      1,
		"PROTOCOL_ANTHROPIC":   2,
		"PROTOCOL_GEMINI":      3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_control_v1_control_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_ALLOW       Decision = 1
	Decision_DECISION_DENY        Decision = 2
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_DENY":        2,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_v1_control_proto_enumTypes[1].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_api_control_v1_control_proto_enumTypes[1]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{1}
}

type InvalidationKind int32

const (
	InvalidationKind_INVALIDATION_KIND_UNSPECIFIED InvalidationKind = 0
	InvalidationKind_INVALIDATION_KIND_API_KEY     InvalidationKind = 1
	InvalidationKind_INVALIDATION_KIND_USER        InvalidationKind = 2
	InvalidationKind_INVALIDATION_KIND_GROUP       InvalidationKind = 3
	InvalidationKind_INVALIDATION_KIND_ACCOUNT     InvalidationKind = 4
	InvalidationKind_INVALIDATION_KIND_POLICY      InvalidationKind = 5
	InvalidationKind_INVALIDATION_KIND_FULL_RESYNC InvalidationKind = 6
)

// Enum value maps for InvalidationKind.
var (
	InvalidationKind_name = map[int32]string{
		0: "INVALIDATION_KIND_UNSPECIFIED",
		1: "INVALIDATION_KIND_API_KEY",
		2: "INVALIDATION_KIND_USER",
		3: "INVALIDATION_KIND_GROUP",
		4: "INVALIDATION_KIND_ACCOUNT",
		5: "INVALIDATION_KIND_POLICY",
		6: "INVALIDATION_KIND_FULL_RESYNC",
	}
	InvalidationKind_value = map[string]int32{
		"INVALIDATION_KIND_UNSPECIFIED": 0,
		"INVALIDATION_KIND_API_KEY":     1,
		"INVALIDATION_KIND_USER":        2,
		"INVALIDATION_KIND_GROUP":       3,
		"INVALIDATION_KIND_ACCOUNT":     4,
		"INVALIDATION_KIND_POLICY":      5,
		"INVALIDATION_KIND_FULL_RESYNC": 6,
	}
)

func (x InvalidationKind) Enum() *InvalidationKind {
	p := new(InvalidationKind)
	*p = x
	return p
}

func (x InvalidationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvalidationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_control_v1_control_proto_enumTypes[2].Descriptor()
}

func (InvalidationKind) Type() protoreflect.EnumType {
	return &file_api_control_v1_control_proto_enumTypes[2]
}

func (x InvalidationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvalidationKind.Descriptor instead.
func (InvalidationKind) EnumDescriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{2}
}

type ResolveAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DataPlaneId   string                 `protobuf:"bytes,2,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAPIKeyRequest) Reset() {
	*x = ResolveAPIKeyRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAPIKeyRequest) ProtoMessage() {}

func (x *ResolveAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ResolveAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveAPIKeyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResolveAPIKeyRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *ResolveAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// RenewAuthGrant rotates a still-valid signed grant without resending the
// plaintext API key. Long-lived WebSocket sessions call it before expiry; the
// control plane revalidates current API-key, user, group, and IP policy state.
type RenewAuthGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DataPlaneId   string                 `protobuf:"bytes,2,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	GrantToken    string                 `protobuf:"bytes,3,opt,name=grant_token,json=grantToken,proto3" json:"grant_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewAuthGrantRequest) Reset() {
	*x = RenewAuthGrantRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAuthGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAuthGrantRequest) ProtoMessage() {}

func (x *RenewAuthGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAuthGrantRequest.ProtoReflect.Descriptor instead.
func (*RenewAuthGrantRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RenewAuthGrantRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenewAuthGrantRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *RenewAuthGrantRequest) GetGrantToken() string {
	if x != nil {
		return x.GrantToken
	}
	return ""
}

type ResolveAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=sup2api.gateway.control.v1.Decision" json:"decision,omitempty"`
	Denial        *Denial                `protobuf:"bytes,2,opt,name=denial,proto3" json:"denial,omitempty"`
	Grant         *AuthGrant             `protobuf:"bytes,3,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAPIKeyResponse) Reset() {
	*x = ResolveAPIKeyResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAPIKeyResponse) ProtoMessage() {}

func (x *ResolveAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ResolveAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveAPIKeyResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *ResolveAPIKeyResponse) GetDenial() *Denial {
	if x != nil {
		return x.Denial
	}
	return nil
}

func (x *ResolveAPIKeyResponse) GetGrant() *AuthGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

// AuthGrant is a short-lived control-plane assertion cached by the data plane.
// grant_token is opaque and must be validated again by OpenRequest.
type AuthGrant struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GrantToken            string                 `protobuf:"bytes,1,opt,name=grant_token,json=grantToken,proto3" json:"grant_token,omitempty"`
	CredentialDigest      string                 `protobuf:"bytes,2,opt,name=credential_digest,json=credentialDigest,proto3" json:"credential_digest,omitempty"`
	ApiKeyId              int64                  `protobuf:"varint,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	UserId                int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId               int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ExpiresAtUnixMs       int64                  `protobuf:"varint,6,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	ApiKeyExpiresAtUnixMs int64                  `protobuf:"varint,7,opt,name=api_key_expires_at_unix_ms,json=apiKeyExpiresAtUnixMs,proto3" json:"api_key_expires_at_unix_ms,omitempty"`
	IpWhitelist           []string               `protobuf:"bytes,8,rep,name=ip_whitelist,json=ipWhitelist,proto3" json:"ip_whitelist,omitempty"`
	IpBlacklist           []string               `protobuf:"bytes,9,rep,name=ip_blacklist,json=ipBlacklist,proto3" json:"ip_blacklist,omitempty"`
	PolicyVersion         string                 `protobuf:"bytes,10,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthGrant) Reset() {
	*x = AuthGrant{}
	mi := &file_api_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGrant) ProtoMessage() {}

func (x *AuthGrant) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGrant.ProtoReflect.Descriptor instead.
func (*AuthGrant) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *AuthGrant) GetGrantToken() string {
	if x != nil {
		return x.GrantToken
	}
	return ""
}

func (x *AuthGrant) GetCredentialDigest() string {
	if x != nil {
		return x.CredentialDigest
	}
	return ""
}

func (x *AuthGrant) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *AuthGrant) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthGrant) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AuthGrant) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *AuthGrant) GetApiKeyExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ApiKeyExpiresAtUnixMs
	}
	return 0
}

func (x *AuthGrant) GetIpWhitelist() []string {
	if x != nil {
		return x.IpWhitelist
	}
	return nil
}

func (x *AuthGrant) GetIpBlacklist() []string {
	if x != nil {
		return x.IpBlacklist
	}
	return nil
}

func (x *AuthGrant) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type OpenRequestRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DataPlaneId          string                 `protobuf:"bytes,2,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	ClientIp             string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent            string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Method               string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Protocol             Protocol               `protobuf:"varint,8,opt,name=protocol,proto3,enum=sup2api.gateway.control.v1.Protocol" json:"protocol,omitempty"`
	RequestedModel       string                 `protobuf:"bytes,9,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	Stream               bool                   `protobuf:"varint,10,opt,name=stream,proto3" json:"stream,omitempty"`
	SessionHash          string                 `protobuf:"bytes,11,opt,name=session_hash,json=sessionHash,proto3" json:"session_hash,omitempty"`
	BodyDigest           string                 `protobuf:"bytes,12,opt,name=body_digest,json=bodyDigest,proto3" json:"body_digest,omitempty"`
	AuthGrantToken       string                 `protobuf:"bytes,13,opt,name=auth_grant_token,json=authGrantToken,proto3" json:"auth_grant_token,omitempty"`
	ApiKeyId             int64                  `protobuf:"varint,14,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	UserId               int64                  `protobuf:"varint,15,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64                  `protobuf:"varint,16,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MaxOutputTokens      int64                  `protobuf:"varint,17,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	RequestContentLength int64                  `protobuf:"varint,18,opt,name=request_content_length,json=requestContentLength,proto3" json:"request_content_length,omitempty"`
	// The control plane needs the requested Anthropic beta capabilities to
	// apply account policy before selecting a provider protocol plugin.
	AnthropicBeta string `protobuf:"bytes,19,opt,name=anthropic_beta,json=anthropicBeta,proto3" json:"anthropic_beta,omitempty"`
	// Anthropic OAuth routing is allowed only when the data plane observed a
	// structurally valid Claude Code metadata.user_id or the official billing
	// attribution block. Request bodies never cross this RPC boundary.
	AnthropicMetadataUserId     string `protobuf:"bytes,20,opt,name=anthropic_metadata_user_id,json=anthropicMetadataUserId,proto3" json:"anthropic_metadata_user_id,omitempty"`
	AnthropicBillingAttribution bool   `protobuf:"varint,21,opt,name=anthropic_billing_attribution,json=anthropicBillingAttribution,proto3" json:"anthropic_billing_attribution,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *OpenRequestRequest) Reset() {
	*x = OpenRequestRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequestRequest) ProtoMessage() {}

func (x *OpenRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequestRequest.ProtoReflect.Descriptor instead.
func (*OpenRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *OpenRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenRequestRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *OpenRequestRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *OpenRequestRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *OpenRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OpenRequestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenRequestRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *OpenRequestRequest) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

func (x *OpenRequestRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *OpenRequestRequest) GetSessionHash() string {
	if x != nil {
		return x.SessionHash
	}
	return ""
}

func (x *OpenRequestRequest) GetBodyDigest() string {
	if x != nil {
		return x.BodyDigest
	}
	return ""
}

func (x *OpenRequestRequest) GetAuthGrantToken() string {
	if x != nil {
		return x.AuthGrantToken
	}
	return ""
}

func (x *OpenRequestRequest) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *OpenRequestRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OpenRequestRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *OpenRequestRequest) GetMaxOutputTokens() int64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *OpenRequestRequest) GetRequestContentLength() int64 {
	if x != nil {
		return x.RequestContentLength
	}
	return 0
}

func (x *OpenRequestRequest) GetAnthropicBeta() string {
	if x != nil {
		return x.AnthropicBeta
	}
	return ""
}

func (x *OpenRequestRequest) GetAnthropicMetadataUserId() string {
	if x != nil {
		return x.AnthropicMetadataUserId
	}
	return ""
}

func (x *OpenRequestRequest) GetAnthropicBillingAttribution() bool {
	if x != nil {
		return x.AnthropicBillingAttribution
	}
	return false
}

type OpenRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=sup2api.gateway.control.v1.Decision" json:"decision,omitempty"`
	Denial        *Denial                `protobuf:"bytes,2,opt,name=denial,proto3" json:"denial,omitempty"`
	Lease         *RequestLease          `protobuf:"bytes,3,opt,name=lease,proto3" json:"lease,omitempty"`
	Plan          *ExecutionPlan         `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequestResponse) Reset() {
	*x = OpenRequestResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequestResponse) ProtoMessage() {}

func (x *OpenRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequestResponse.ProtoReflect.Descriptor instead.
func (*OpenRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *OpenRequestResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *OpenRequestResponse) GetDenial() *Denial {
	if x != nil {
		return x.Denial
	}
	return nil
}

func (x *OpenRequestResponse) GetLease() *RequestLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *OpenRequestResponse) GetPlan() *ExecutionPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type Denial struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HttpStatus        int32                  `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RetryAfterSeconds int32                  `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Denial) Reset() {
	*x = Denial{}
	mi := &file_api_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Denial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denial) ProtoMessage() {}

func (x *Denial) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denial.ProtoReflect.Descriptor instead.
func (*Denial) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Denial) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *Denial) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Denial) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Denial) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

type RequestLease struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LeaseId                string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ExpiresAtUnixMs        int64                  `protobuf:"varint,2,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	ApiKeyId               int64                  `protobuf:"varint,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	UserId                 int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId                int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AccountId              int64                  `protobuf:"varint,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PricingVersion         string                 `protobuf:"bytes,7,opt,name=pricing_version,json=pricingVersion,proto3" json:"pricing_version,omitempty"`
	PolicyVersion          string                 `protobuf:"bytes,8,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	BillingReservationId   string                 `protobuf:"bytes,9,opt,name=billing_reservation_id,json=billingReservationId,proto3" json:"billing_reservation_id,omitempty"`
	ReservedAmountMicrousd int64                  `protobuf:"varint,10,opt,name=reserved_amount_microusd,json=reservedAmountMicrousd,proto3" json:"reserved_amount_microusd,omitempty"`
	BillingMode            string                 `protobuf:"bytes,11,opt,name=billing_mode,json=billingMode,proto3" json:"billing_mode,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RequestLease) Reset() {
	*x = RequestLease{}
	mi := &file_api_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLease) ProtoMessage() {}

func (x *RequestLease) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLease.ProtoReflect.Descriptor instead.
func (*RequestLease) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *RequestLease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RequestLease) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *RequestLease) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *RequestLease) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RequestLease) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RequestLease) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RequestLease) GetPricingVersion() string {
	if x != nil {
		return x.PricingVersion
	}
	return ""
}

func (x *RequestLease) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *RequestLease) GetBillingReservationId() string {
	if x != nil {
		return x.BillingReservationId
	}
	return ""
}

func (x *RequestLease) GetReservedAmountMicrousd() int64 {
	if x != nil {
		return x.ReservedAmountMicrousd
	}
	return 0
}

func (x *RequestLease) GetBillingMode() string {
	if x != nil {
		return x.BillingMode
	}
	return ""
}

type ExecutionPlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpstreamUrl      string                 `protobuf:"bytes,1,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	UpstreamMethod   string                 `protobuf:"bytes,2,opt,name=upstream_method,json=upstreamMethod,proto3" json:"upstream_method,omitempty"`
	UpstreamHost     string                 `protobuf:"bytes,3,opt,name=upstream_host,json=upstreamHost,proto3" json:"upstream_host,omitempty"`
	UpstreamHeaders  map[string]string      `protobuf:"bytes,4,rep,name=upstream_headers,json=upstreamHeaders,proto3" json:"upstream_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedModel      string                 `protobuf:"bytes,5,opt,name=mapped_model,json=mappedModel,proto3" json:"mapped_model,omitempty"`
	TransportProfile string                 `protobuf:"bytes,6,opt,name=transport_profile,json=transportProfile,proto3" json:"transport_profile,omitempty"`
	ProxyProfile     string                 `protobuf:"bytes,7,opt,name=proxy_profile,json=proxyProfile,proto3" json:"proxy_profile,omitempty"`
	MaxAttempts      int32                  `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// proxy_url is a short-lived execution credential delivered only over the
	// private control channel. The data plane never persists it in settlement WAL.
	ProxyUrl string `protobuf:"bytes,9,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	// protocol_profile selects a Caddy module under sup2api.protocols. The
	// default is passthrough; provider-specific request/response transformations
	// must use an explicit profile and fail closed when it is unavailable.
	ProtocolProfile string `protobuf:"bytes,10,opt,name=protocol_profile,json=protocolProfile,proto3" json:"protocol_profile,omitempty"`
	// Short-lived provider execution options. These travel only over the private
	// control channel and, like upstream credentials, must never be logged or
	// persisted in the data-plane settlement WAL.
	ProtocolOptions map[string]string      `protobuf:"bytes,11,rep,name=protocol_options,json=protocolOptions,proto3" json:"protocol_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TlsFingerprint  *TLSFingerprintProfile `protobuf:"bytes,12,opt,name=tls_fingerprint,json=tlsFingerprint,proto3" json:"tls_fingerprint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_api_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionPlan) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *ExecutionPlan) GetUpstreamMethod() string {
	if x != nil {
		return x.UpstreamMethod
	}
	return ""
}

func (x *ExecutionPlan) GetUpstreamHost() string {
	if x != nil {
		return x.UpstreamHost
	}
	return ""
}

func (x *ExecutionPlan) GetUpstreamHeaders() map[string]string {
	if x != nil {
		return x.UpstreamHeaders
	}
	return nil
}

func (x *ExecutionPlan) GetMappedModel() string {
	if x != nil {
		return x.MappedModel
	}
	return ""
}

func (x *ExecutionPlan) GetTransportProfile() string {
	if x != nil {
		return x.TransportProfile
	}
	return ""
}

func (x *ExecutionPlan) GetProxyProfile() string {
	if x != nil {
		return x.ProxyProfile
	}
	return ""
}

func (x *ExecutionPlan) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ExecutionPlan) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *ExecutionPlan) GetProtocolProfile() string {
	if x != nil {
		return x.ProtocolProfile
	}
	return ""
}

func (x *ExecutionPlan) GetProtocolOptions() map[string]string {
	if x != nil {
		return x.ProtocolOptions
	}
	return nil
}

func (x *ExecutionPlan) GetTlsFingerprint() *TLSFingerprintProfile {
	if x != nil {
		return x.TlsFingerprint
	}
	return nil
}

// SignBedrockRequest signs only a payload digest and the authority-owned
// execution target. The Bedrock request body and AWS credentials never cross
// the control-plane boundary.
type SignBedrockRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	UpstreamUrl   string                 `protobuf:"bytes,5,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	PayloadSha256 string                 `protobuf:"bytes,6,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignBedrockRequestRequest) Reset() {
	*x = SignBedrockRequestRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignBedrockRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignBedrockRequestRequest) ProtoMessage() {}

func (x *SignBedrockRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignBedrockRequestRequest.ProtoReflect.Descriptor instead.
func (*SignBedrockRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *SignBedrockRequestRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *SignBedrockRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignBedrockRequestRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *SignBedrockRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SignBedrockRequestRequest) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *SignBedrockRequestRequest) GetPayloadSha256() string {
	if x != nil {
		return x.PayloadSha256
	}
	return ""
}

func (x *SignBedrockRequestRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type SignBedrockRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=sup2api.gateway.control.v1.Decision" json:"decision,omitempty"`
	Denial        *Denial                `protobuf:"bytes,2,opt,name=denial,proto3" json:"denial,omitempty"`
	SignedHeaders map[string]string      `protobuf:"bytes,3,rep,name=signed_headers,json=signedHeaders,proto3" json:"signed_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignBedrockRequestResponse) Reset() {
	*x = SignBedrockRequestResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignBedrockRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignBedrockRequestResponse) ProtoMessage() {}

func (x *SignBedrockRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignBedrockRequestResponse.ProtoReflect.Descriptor instead.
func (*SignBedrockRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *SignBedrockRequestResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *SignBedrockRequestResponse) GetDenial() *Denial {
	if x != nil {
		return x.Denial
	}
	return nil
}

func (x *SignBedrockRequestResponse) GetSignedHeaders() map[string]string {
	if x != nil {
		return x.SignedHeaders
	}
	return nil
}

// TLSFingerprintProfile is an immutable, short-lived execution snapshot. The
// control plane resolves database profile IDs before issuing the plan, keeping
// the data plane free of database access and configuration races.
type TLSFingerprintProfile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProfileKey          string                 `protobuf:"bytes,1,opt,name=profile_key,json=profileKey,proto3" json:"profile_key,omitempty"`
	EnableGrease        bool                   `protobuf:"varint,2,opt,name=enable_grease,json=enableGrease,proto3" json:"enable_grease,omitempty"`
	CipherSuites        []uint32               `protobuf:"varint,3,rep,packed,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	Curves              []uint32               `protobuf:"varint,4,rep,packed,name=curves,proto3" json:"curves,omitempty"`
	PointFormats        []uint32               `protobuf:"varint,5,rep,packed,name=point_formats,json=pointFormats,proto3" json:"point_formats,omitempty"`
	SignatureAlgorithms []uint32               `protobuf:"varint,6,rep,packed,name=signature_algorithms,json=signatureAlgorithms,proto3" json:"signature_algorithms,omitempty"`
	AlpnProtocols       []string               `protobuf:"bytes,7,rep,name=alpn_protocols,json=alpnProtocols,proto3" json:"alpn_protocols,omitempty"`
	SupportedVersions   []uint32               `protobuf:"varint,8,rep,packed,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	KeyShareGroups      []uint32               `protobuf:"varint,9,rep,packed,name=key_share_groups,json=keyShareGroups,proto3" json:"key_share_groups,omitempty"`
	PskModes            []uint32               `protobuf:"varint,10,rep,packed,name=psk_modes,json=pskModes,proto3" json:"psk_modes,omitempty"`
	Extensions          []uint32               `protobuf:"varint,11,rep,packed,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TLSFingerprintProfile) Reset() {
	*x = TLSFingerprintProfile{}
	mi := &file_api_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSFingerprintProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSFingerprintProfile) ProtoMessage() {}

func (x *TLSFingerprintProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSFingerprintProfile.ProtoReflect.Descriptor instead.
func (*TLSFingerprintProfile) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *TLSFingerprintProfile) GetProfileKey() string {
	if x != nil {
		return x.ProfileKey
	}
	return ""
}

func (x *TLSFingerprintProfile) GetEnableGrease() bool {
	if x != nil {
		return x.EnableGrease
	}
	return false
}

func (x *TLSFingerprintProfile) GetCipherSuites() []uint32 {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *TLSFingerprintProfile) GetCurves() []uint32 {
	if x != nil {
		return x.Curves
	}
	return nil
}

func (x *TLSFingerprintProfile) GetPointFormats() []uint32 {
	if x != nil {
		return x.PointFormats
	}
	return nil
}

func (x *TLSFingerprintProfile) GetSignatureAlgorithms() []uint32 {
	if x != nil {
		return x.SignatureAlgorithms
	}
	return nil
}

func (x *TLSFingerprintProfile) GetAlpnProtocols() []string {
	if x != nil {
		return x.AlpnProtocols
	}
	return nil
}

func (x *TLSFingerprintProfile) GetSupportedVersions() []uint32 {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

func (x *TLSFingerprintProfile) GetKeyShareGroups() []uint32 {
	if x != nil {
		return x.KeyShareGroups
	}
	return nil
}

func (x *TLSFingerprintProfile) GetPskModes() []uint32 {
	if x != nil {
		return x.PskModes
	}
	return nil
}

func (x *TLSFingerprintProfile) GetExtensions() []uint32 {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *RenewLeaseRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *RenewLeaseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenewLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type RenewLeaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Renewed         bool                   `protobuf:"varint,1,opt,name=renewed,proto3" json:"renewed,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,2,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *RenewLeaseResponse) GetRenewed() bool {
	if x != nil {
		return x.Renewed
	}
	return false
}

func (x *RenewLeaseResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type AbortRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequestRequest) Reset() {
	*x = AbortRequestRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequestRequest) ProtoMessage() {}

func (x *AbortRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequestRequest.ProtoReflect.Descriptor instead.
func (*AbortRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *AbortRequestRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *AbortRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AbortRequestRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AbortRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequestResponse) Reset() {
	*x = AbortRequestResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequestResponse) ProtoMessage() {}

func (x *AbortRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequestResponse.ProtoReflect.Descriptor instead.
func (*AbortRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *AbortRequestResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type SettleRequestRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId         string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	RequestId           string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LeaseId             string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	AccountId           int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RequestedModel      string                 `protobuf:"bytes,5,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	MappedModel         string                 `protobuf:"bytes,6,opt,name=mapped_model,json=mappedModel,proto3" json:"mapped_model,omitempty"`
	PricingVersion      string                 `protobuf:"bytes,7,opt,name=pricing_version,json=pricingVersion,proto3" json:"pricing_version,omitempty"`
	Usage               *Usage                 `protobuf:"bytes,8,opt,name=usage,proto3" json:"usage,omitempty"`
	Upstream            *UpstreamResult        `protobuf:"bytes,9,opt,name=upstream,proto3" json:"upstream,omitempty"`
	StartedAtUnixMs     int64                  `protobuf:"varint,10,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	FirstByteAtUnixMs   int64                  `protobuf:"varint,11,opt,name=first_byte_at_unix_ms,json=firstByteAtUnixMs,proto3" json:"first_byte_at_unix_ms,omitempty"`
	FinishedAtUnixMs    int64                  `protobuf:"varint,12,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	ClientCancelled     bool                   `protobuf:"varint,13,opt,name=client_cancelled,json=clientCancelled,proto3" json:"client_cancelled,omitempty"`
	DataPlaneInstanceId string                 `protobuf:"bytes,14,opt,name=data_plane_instance_id,json=dataPlaneInstanceId,proto3" json:"data_plane_instance_id,omitempty"`
	ServiceTier         string                 `protobuf:"bytes,15,opt,name=service_tier,json=serviceTier,proto3" json:"service_tier,omitempty"`
	ReasoningEffort     string                 `protobuf:"bytes,16,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	OpenaiWsMode        bool                   `protobuf:"varint,17,opt,name=openai_ws_mode,json=openaiWsMode,proto3" json:"openai_ws_mode,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SettleRequestRequest) Reset() {
	*x = SettleRequestRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequestRequest) ProtoMessage() {}

func (x *SettleRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequestRequest.ProtoReflect.Descriptor instead.
func (*SettleRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *SettleRequestRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *SettleRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SettleRequestRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *SettleRequestRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SettleRequestRequest) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

func (x *SettleRequestRequest) GetMappedModel() string {
	if x != nil {
		return x.MappedModel
	}
	return ""
}

func (x *SettleRequestRequest) GetPricingVersion() string {
	if x != nil {
		return x.PricingVersion
	}
	return ""
}

func (x *SettleRequestRequest) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *SettleRequestRequest) GetUpstream() *UpstreamResult {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *SettleRequestRequest) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *SettleRequestRequest) GetFirstByteAtUnixMs() int64 {
	if x != nil {
		return x.FirstByteAtUnixMs
	}
	return 0
}

func (x *SettleRequestRequest) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

func (x *SettleRequestRequest) GetClientCancelled() bool {
	if x != nil {
		return x.ClientCancelled
	}
	return false
}

func (x *SettleRequestRequest) GetDataPlaneInstanceId() string {
	if x != nil {
		return x.DataPlaneInstanceId
	}
	return ""
}

func (x *SettleRequestRequest) GetServiceTier() string {
	if x != nil {
		return x.ServiceTier
	}
	return ""
}

func (x *SettleRequestRequest) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *SettleRequestRequest) GetOpenaiWsMode() bool {
	if x != nil {
		return x.OpenaiWsMode
	}
	return false
}

type Usage struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	InputTokens            int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens           int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens        int64                  `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheCreationTokens    int64                  `protobuf:"varint,4,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	ReasoningTokens        int64                  `protobuf:"varint,5,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	ResponseBytes          int64                  `protobuf:"varint,6,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	CacheCreation_5MTokens int64                  `protobuf:"varint,7,opt,name=cache_creation_5m_tokens,json=cacheCreation5mTokens,proto3" json:"cache_creation_5m_tokens,omitempty"`
	CacheCreation_1HTokens int64                  `protobuf:"varint,8,opt,name=cache_creation_1h_tokens,json=cacheCreation1hTokens,proto3" json:"cache_creation_1h_tokens,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_api_control_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *Usage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *Usage) GetCacheCreationTokens() int64 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

func (x *Usage) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *Usage) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

func (x *Usage) GetCacheCreation_5MTokens() int64 {
	if x != nil {
		return x.CacheCreation_5MTokens
	}
	return 0
}

func (x *Usage) GetCacheCreation_1HTokens() int64 {
	if x != nil {
		return x.CacheCreation_1HTokens
	}
	return 0
}

type UpstreamResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusCode     int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	RateLimitReset string                 `protobuf:"bytes,3,opt,name=rate_limit_reset,json=rateLimitReset,proto3" json:"rate_limit_reset,omitempty"`
	Attempts       int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpstreamResult) Reset() {
	*x = UpstreamResult{}
	mi := &file_api_control_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamResult) ProtoMessage() {}

func (x *UpstreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamResult.ProtoReflect.Descriptor instead.
func (*UpstreamResult) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *UpstreamResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpstreamResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *UpstreamResult) GetRateLimitReset() string {
	if x != nil {
		return x.RateLimitReset
	}
	return ""
}

func (x *UpstreamResult) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type SettleRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequestResponse) Reset() {
	*x = SettleRequestResponse{}
	mi := &file_api_control_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequestResponse) ProtoMessage() {}

func (x *SettleRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequestResponse.ProtoReflect.Descriptor instead.
func (*SettleRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *SettleRequestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SettleRequestResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type WatchInvalidationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPlaneId   string                 `protobuf:"bytes,1,opt,name=data_plane_id,json=dataPlaneId,proto3" json:"data_plane_id,omitempty"`
	AfterSequence int64                  `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInvalidationsRequest) Reset() {
	*x = WatchInvalidationsRequest{}
	mi := &file_api_control_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInvalidationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInvalidationsRequest) ProtoMessage() {}

func (x *WatchInvalidationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInvalidationsRequest.ProtoReflect.Descriptor instead.
func (*WatchInvalidationsRequest) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *WatchInvalidationsRequest) GetDataPlaneId() string {
	if x != nil {
		return x.DataPlaneId
	}
	return ""
}

func (x *WatchInvalidationsRequest) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

type InvalidationEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Kind     InvalidationKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=sup2api.gateway.control.v1.InvalidationKind" json:"kind,omitempty"`
	// API_KEY subjects are SHA-256 credential digests; USER/GROUP subjects are
	// decimal IDs. POLICY and FULL_RESYNC ignore subject.
	Subject          string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Version          string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	OccurredAtUnixMs int64  `protobuf:"varint,5,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvalidationEvent) Reset() {
	*x = InvalidationEvent{}
	mi := &file_api_control_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidationEvent) ProtoMessage() {}

func (x *InvalidationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidationEvent.ProtoReflect.Descriptor instead.
func (*InvalidationEvent) Descriptor() ([]byte, []int) {
	return file_api_control_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *InvalidationEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *InvalidationEvent) GetKind() InvalidationKind {
	if x != nil {
		return x.Kind
	}
	return InvalidationKind_INVALIDATION_KIND_UNSPECIFIED
}

func (x *InvalidationEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InvalidationEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InvalidationEvent) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

var File_api_control_v1_control_proto protoreflect.FileDescriptor

const file_api_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1capi/control/v1/control.proto\x12\x1asup2api.gateway.control.v1\"r\n" +
	"\x14ResolveAPIKeyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\"\n" +
	"\rdata_plane_id\x18\x02 \x01(\tR\vdataPlaneId\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"{\n" +
	"\x15RenewAuthGrantRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\"\n" +
	"\rdata_plane_id\x18\x02 \x01(\tR\vdataPlaneId\x12\x1f\n" +
	"\vgrant_token\x18\x03 \x01(\tR\n" +
	"grantToken\"\xd2\x01\n" +
	"\x15ResolveAPIKeyResponse\x12@\n" +
	"\bdecision\x18\x01 \x01(\x0e2$.sup2api.gateway.control.v1.DecisionR\bdecision\x12:\n" +
	"\x06denial\x18\x02 \x01(\v2\".sup2api.gateway.control.v1.DenialR\x06denial\x12;\n" +
	"\x05grant\x18\x03 \x01(\v2%.sup2api.gateway.control.v1.AuthGrantR\x05grant\"\x80\x03\n" +
	"\tAuthGrant\x12\x1f\n" +
	"\vgrant_token\x18\x01 \x01(\tR\n" +
	"grantToken\x12+\n" +
	"\x11credential_digest\x18\x02 \x01(\tR\x10credentialDigest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\x03R\bapiKeyId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12+\n" +
	"\x12expires_at_unix_ms\x18\x06 \x01(\x03R\x0fexpiresAtUnixMs\x129\n" +
	"\x1aapi_key_expires_at_unix_ms\x18\a \x01(\x03R\x15apiKeyExpiresAtUnixMs\x12!\n" +
	"\fip_whitelist\x18\b \x03(\tR\vipWhitelist\x12!\n" +
	"\fip_blacklist\x18\t \x03(\tR\vipBlacklist\x12%\n" +
	"\x0epolicy_version\x18\n" +
	" \x01(\tR\rpolicyVersion\"\x9b\x06\n" +
	"\x12OpenRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\"\n" +
	"\rdata_plane_id\x18\x02 \x01(\tR\vdataPlaneId\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12@\n" +
	"\bprotocol\x18\b \x01(\x0e2$.sup2api.gateway.control.v1.ProtocolR\bprotocol\x12'\n" +
	"\x0frequested_model\x18\t \x01(\tR\x0erequestedModel\x12\x16\n" +
	"\x06stream\x18\n" +
	" \x01(\bR\x06stream\x12!\n" +
	"\fsession_hash\x18\v \x01(\tR\vsessionHash\x12\x1f\n" +
	"\vbody_digest\x18\f \x01(\tR\n" +
	"bodyDigest\x12(\n" +
	"\x10auth_grant_token\x18\r \x01(\tR\x0eauthGrantToken\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x0e \x01(\x03R\bapiKeyId\x12\x17\n" +
	"\auser_id\x18\x0f \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x10 \x01(\x03R\agroupId\x12*\n" +
	"\x11max_output_tokens\x18\x11 \x01(\x03R\x0fmaxOutputTokens\x124\n" +
	"\x16request_content_length\x18\x12 \x01(\x03R\x14requestContentLength\x12%\n" +
	"\x0eanthropic_beta\x18\x13 \x01(\tR\ranthropicBeta\x12;\n" +
	"\x1aanthropic_metadata_user_id\x18\x14 \x01(\tR\x17anthropicMetadataUserId\x12B\n" +
	"\x1danthropic_billing_attribution\x18\x15 \x01(\bR\x1banthropicBillingAttributionJ\x04\b\x03\x10\x04R\aapi_key\"\x92\x02\n" +
	"\x13OpenRequestResponse\x12@\n" +
	"\bdecision\x18\x01 \x01(\x0e2$.sup2api.gateway.control.v1.DecisionR\bdecision\x12:\n" +
	"\x06denial\x18\x02 \x01(\v2\".sup2api.gateway.control.v1.DenialR\x06denial\x12>\n" +
	"\x05lease\x18\x03 \x01(\v2(.sup2api.gateway.control.v1.RequestLeaseR\x05lease\x12=\n" +
	"\x04plan\x18\x04 \x01(\v2).sup2api.gateway.control.v1.ExecutionPlanR\x04plan\"\x92\x01\n" +
	"\x06Denial\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\x05R\n" +
	"httpStatus\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\x05R\x11retryAfterSeconds\"\xaa\x03\n" +
	"\fRequestLease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12+\n" +
	"\x12expires_at_unix_ms\x18\x02 \x01(\x03R\x0fexpiresAtUnixMs\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\x03R\bapiKeyId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\x03R\taccountId\x12'\n" +
	"\x0fpricing_version\x18\a \x01(\tR\x0epricingVersion\x12%\n" +
	"\x0epolicy_version\x18\b \x01(\tR\rpolicyVersion\x124\n" +
	"\x16billing_reservation_id\x18\t \x01(\tR\x14billingReservationId\x128\n" +
	"\x18reserved_amount_microusd\x18\n" +
	" \x01(\x03R\x16reservedAmountMicrousd\x12!\n" +
	"\fbilling_mode\x18\v \x01(\tR\vbillingMode\"\x9a\x06\n" +
	"\rExecutionPlan\x12!\n" +
	"\fupstream_url\x18\x01 \x01(\tR\vupstreamUrl\x12'\n" +
	"\x0fupstream_method\x18\x02 \x01(\tR\x0eupstreamMethod\x12#\n" +
	"\rupstream_host\x18\x03 \x01(\tR\fupstreamHost\x12i\n" +
	"\x10upstream_headers\x18\x04 \x03(\v2>.sup2api.gateway.control.v1.ExecutionPlan.UpstreamHeadersEntryR\x0fupstreamHeaders\x12!\n" +
	"\fmapped_model\x18\x05 \x01(\tR\vmappedModel\x12+\n" +
	"\x11transport_profile\x18\x06 \x01(\tR\x10transportProfile\x12#\n" +
	"\rproxy_profile\x18\a \x01(\tR\fproxyProfile\x12!\n" +
	"\fmax_attempts\x18\b \x01(\x05R\vmaxAttempts\x12\x1b\n" +
	"\tproxy_url\x18\t \x01(\tR\bproxyUrl\x12)\n" +
	"\x10protocol_profile\x18\n" +
	" \x01(\tR\x0fprotocolProfile\x12i\n" +
	"\x10protocol_options\x18\v \x03(\v2>.sup2api.gateway.control.v1.ExecutionPlan.ProtocolOptionsEntryR\x0fprotocolOptions\x12Z\n" +
	"\x0ftls_fingerprint\x18\f \x01(\v21.sup2api.gateway.control.v1.TLSFingerprintProfileR\x0etlsFingerprint\x1aB\n" +
	"\x14UpstreamHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ProtocolOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x02\n" +
	"\x19SignBedrockRequestRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12!\n" +
	"\fupstream_url\x18\x05 \x01(\tR\vupstreamUrl\x12%\n" +
	"\x0epayload_sha256\x18\x06 \x01(\tR\rpayloadSha256\x12\\\n" +
	"\aheaders\x18\a \x03(\v2B.sup2api.gateway.control.v1.SignBedrockRequestRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x02\n" +
	"\x1aSignBedrockRequestResponse\x12@\n" +
	"\bdecision\x18\x01 \x01(\x0e2$.sup2api.gateway.control.v1.DecisionR\bdecision\x12:\n" +
	"\x06denial\x18\x02 \x01(\v2\".sup2api.gateway.control.v1.DenialR\x06denial\x12p\n" +
	"\x0esigned_headers\x18\x03 \x03(\v2I.sup2api.gateway.control.v1.SignBedrockRequestResponse.SignedHeadersEntryR\rsignedHeaders\x1a@\n" +
	"\x12SignedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x03\n" +
	"\x15TLSFingerprintProfile\x12\x1f\n" +
	"\vprofile_key\x18\x01 \x01(\tR\n" +
	"profileKey\x12#\n" +
	"\renable_grease\x18\x02 \x01(\bR\fenableGrease\x12#\n" +
	"\rcipher_suites\x18\x03 \x03(\rR\fcipherSuites\x12\x16\n" +
	"\x06curves\x18\x04 \x03(\rR\x06curves\x12#\n" +
	"\rpoint_formats\x18\x05 \x03(\rR\fpointFormats\x121\n" +
	"\x14signature_algorithms\x18\x06 \x03(\rR\x13signatureAlgorithms\x12%\n" +
	"\x0ealpn_protocols\x18\a \x03(\tR\ralpnProtocols\x12-\n" +
	"\x12supported_versions\x18\b \x03(\rR\x11supportedVersions\x12(\n" +
	"\x10key_share_groups\x18\t \x03(\rR\x0ekeyShareGroups\x12\x1b\n" +
	"\tpsk_modes\x18\n" +
	" \x03(\rR\bpskModes\x12\x1e\n" +
	"\n" +
	"extensions\x18\v \x03(\rR\n" +
	"extensions\"q\n" +
	"\x11RenewLeaseRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\"[\n" +
	"\x12RenewLeaseResponse\x12\x18\n" +
	"\arenewed\x18\x01 \x01(\bR\arenewed\x12+\n" +
	"\x12expires_at_unix_ms\x18\x02 \x01(\x03R\x0fexpiresAtUnixMs\"\x8b\x01\n" +
	"\x13AbortRequestRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"2\n" +
	"\x14AbortRequestResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\xeb\x05\n" +
	"\x14SettleRequestRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12'\n" +
	"\x0frequested_model\x18\x05 \x01(\tR\x0erequestedModel\x12!\n" +
	"\fmapped_model\x18\x06 \x01(\tR\vmappedModel\x12'\n" +
	"\x0fpricing_version\x18\a \x01(\tR\x0epricingVersion\x127\n" +
	"\x05usage\x18\b \x01(\v2!.sup2api.gateway.control.v1.UsageR\x05usage\x12F\n" +
	"\bupstream\x18\t \x01(\v2*.sup2api.gateway.control.v1.UpstreamResultR\bupstream\x12+\n" +
	"\x12started_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fstartedAtUnixMs\x120\n" +
	"\x15first_byte_at_unix_ms\x18\v \x01(\x03R\x11firstByteAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\f \x01(\x03R\x10finishedAtUnixMs\x12)\n" +
	"\x10client_cancelled\x18\r \x01(\bR\x0fclientCancelled\x123\n" +
	"\x16data_plane_instance_id\x18\x0e \x01(\tR\x13dataPlaneInstanceId\x12!\n" +
	"\fservice_tier\x18\x0f \x01(\tR\vserviceTier\x12)\n" +
	"\x10reasoning_effort\x18\x10 \x01(\tR\x0freasoningEffort\x12$\n" +
	"\x0eopenai_ws_mode\x18\x11 \x01(\bR\fopenaiWsMode\"\xf3\x02\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x03R\x0fcacheReadTokens\x122\n" +
	"\x15cache_creation_tokens\x18\x04 \x01(\x03R\x13cacheCreationTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x05 \x01(\x03R\x0freasoningTokens\x12%\n" +
	"\x0eresponse_bytes\x18\x06 \x01(\x03R\rresponseBytes\x127\n" +
	"\x18cache_creation_5m_tokens\x18\a \x01(\x03R\x15cacheCreation5mTokens\x127\n" +
	"\x18cache_creation_1h_tokens\x18\b \x01(\x03R\x15cacheCreation1hTokens\"\x96\x01\n" +
	"\x0eUpstreamResult\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12(\n" +
	"\x10rate_limit_reset\x18\x03 \x01(\tR\x0erateLimitReset\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\"Q\n" +
	"\x15SettleRequestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\"f\n" +
	"\x19WatchInvalidationsRequest\x12\"\n" +
	"\rdata_plane_id\x18\x01 \x01(\tR\vdataPlaneId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x03R\rafterSequence\"\xd4\x01\n" +
	"\x11InvalidationEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12@\n" +
	"\x04kind\x18\x02 \x01(\x0e2,.sup2api.gateway.control.v1.InvalidationKindR\x04kind\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12-\n" +
	"\x13occurred_at_unix_ms\x18\x05 \x01(\x03R\x10occurredAtUnixMs*f\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROTOCOL_OPENAI\x10\x01\x12\x16\n" +
	"\x12PROTOCOL_ANTHROPIC\x10\x02\x12\x13\n" +
	"\x0fPROTOCOL_GEMINI\x10\x03*K\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02*\xed\x01\n" +
	"\x10InvalidationKind\x12!\n" +
	"\x1dINVALIDATION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INVALIDATION_KIND_API_KEY\x10\x01\x12\x1a\n" +
	"\x16INVALIDATION_KIND_USER\x10\x02\x12\x1b\n" +
	"\x17INVALIDATION_KIND_GROUP\x10\x03\x12\x1d\n" +
	"\x19INVALIDATION_KIND_ACCOUNT\x10\x04\x12\x1c\n" +
	"\x18INVALIDATION_KIND_POLICY\x10\x05\x12!\n" +
	"\x1dINVALIDATION_KIND_FULL_RESYNC\x10\x062\xca\a\n" +
	"\x10DataPlaneControl\x12t\n" +
	"\rResolveAPIKey\x120.sup2api.gateway.control.v1.ResolveAPIKeyRequest\x1a1.sup2api.gateway.control.v1.ResolveAPIKeyResponse\x12v\n" +
	"\x0eRenewAuthGrant\x121.sup2api.gateway.control.v1.RenewAuthGrantRequest\x1a1.sup2api.gateway.control.v1.ResolveAPIKeyResponse\x12n\n" +
	"\vOpenRequest\x12..sup2api.gateway.control.v1.OpenRequestRequest\x1a/.sup2api.gateway.control.v1.OpenRequestResponse\x12\x83\x01\n" +
	"\x12SignBedrockRequest\x125.sup2api.gateway.control.v1.SignBedrockRequestRequest\x1a6.sup2api.gateway.control.v1.SignBedrockRequestResponse\x12k\n" +
	"\n" +
	"RenewLease\x12-.sup2api.gateway.control.v1.RenewLeaseRequest\x1a..sup2api.gateway.control.v1.RenewLeaseResponse\x12q\n" +
	"\fAbortRequest\x12/.sup2api.gateway.control.v1.AbortRequestRequest\x1a0.sup2api.gateway.control.v1.AbortRequestResponse\x12t\n" +
	"\rSettleRequest\x120.sup2api.gateway.control.v1.SettleRequestRequest\x1a1.sup2api.gateway.control.v1.SettleRequestResponse\x12|\n" +
	"\x12WatchInvalidations\x125.sup2api.gateway.control.v1.WatchInvalidationsRequest\x1a-.sup2api.gateway.control.v1.InvalidationEvent0\x01BEZCgithub.com/Sub2API-Devs/sup2api/ai-gateway/gen/control/v1;controlv1b\x06proto3"

var (
	file_api_control_v1_control_proto_rawDescOnce sync.Once
	file_api_control_v1_control_proto_rawDescData []byte
)

func file_api_control_v1_control_proto_rawDescGZIP() []byte {
	file_api_control_v1_control_proto_rawDescOnce.Do(func() {
		file_api_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)))
	})
	return file_api_control_v1_control_proto_rawDescData
}

var file_api_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_control_v1_control_proto_goTypes = []any{
	(Protocol)(0),                      // 0: sup2api.gateway.control.v1.Protocol
	(Decision)(0),                      // 1: sup2api.gateway.control.v1.Decision
	(InvalidationKind)(0),              // 2: sup2api.gateway.control.v1.InvalidationKind
	(*ResolveAPIKeyRequest)(nil),       // 3: sup2api.gateway.control.v1.ResolveAPIKeyRequest
	(*RenewAuthGrantRequest)(nil),      // 4: sup2api.gateway.control.v1.RenewAuthGrantRequest
	(*ResolveAPIKeyResponse)(nil),      // 5: sup2api.gateway.control.v1.ResolveAPIKeyResponse
	(*AuthGrant)(nil),                  // 6: sup2api.gateway.control.v1.AuthGrant
	(*OpenRequestRequest)(nil),         // 7: sup2api.gateway.control.v1.OpenRequestRequest
	(*OpenRequestResponse)(nil),        // 8: sup2api.gateway.control.v1.OpenRequestResponse
	(*Denial)(nil),                     // 9: sup2api.gateway.control.v1.Denial
	(*RequestLease)(nil),               // 10: sup2api.gateway.control.v1.RequestLease
	(*ExecutionPlan)(nil),              // 11: sup2api.gateway.control.v1.ExecutionPlan
	(*SignBedrockRequestRequest)(nil),  // 12: sup2api.gateway.control.v1.SignBedrockRequestRequest
	(*SignBedrockRequestResponse)(nil), // 13: sup2api.gateway.control.v1.SignBedrockRequestResponse
	(*TLSFingerprintProfile)(nil),      // 14: sup2api.gateway.control.v1.TLSFingerprintProfile
	(*RenewLeaseRequest)(nil),          // 15: sup2api.gateway.control.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),         // 16: sup2api.gateway.control.v1.RenewLeaseResponse
	(*AbortRequestRequest)(nil),        // 17: sup2api.gateway.control.v1.AbortRequestRequest
	(*AbortRequestResponse)(nil),       // 18: sup2api.gateway.control.v1.AbortRequestResponse
	(*SettleRequestRequest)(nil),       // 19: sup2api.gateway.control.v1.SettleRequestRequest
	(*Usage)(nil),                      // 20: sup2api.gateway.control.v1.Usage
	(*UpstreamResult)(nil),             // 21: sup2api.gateway.control.v1.UpstreamResult
	(*SettleRequestResponse)(nil),      // 22: sup2api.gateway.control.v1.SettleRequestResponse
	(*WatchInvalidationsRequest)(nil),  // 23: sup2api.gateway.control.v1.WatchInvalidationsRequest
	(*InvalidationEvent)(nil),          // 24: sup2api.gateway.control.v1.InvalidationEvent
	nil,                                // 25: sup2api.gateway.control.v1.ExecutionPlan.UpstreamHeadersEntry
	nil,                                // 26: sup2api.gateway.control.v1.ExecutionPlan.ProtocolOptionsEntry
	nil,                                // 27: sup2api.gateway.control.v1.SignBedrockRequestRequest.HeadersEntry
	nil,                                // 28: sup2api.gateway.control.v1.SignBedrockRequestResponse.SignedHeadersEntry
}
var file_api_control_v1_control_proto_depIdxs = []int32{
	1,  // 0: sup2api.gateway.control.v1.ResolveAPIKeyResponse.decision:type_name -> sup2api.gateway.control.v1.Decision
	9,  // 1: sup2api.gateway.control.v1.ResolveAPIKeyResponse.denial:type_name -> sup2api.gateway.control.v1.Denial
	6,  // 2: sup2api.gateway.control.v1.ResolveAPIKeyResponse.grant:type_name -> sup2api.gateway.control.v1.AuthGrant
	0,  // 3: sup2api.gateway.control.v1.OpenRequestRequest.protocol:type_name -> sup2api.gateway.control.v1.Protocol
	1,  // 4: sup2api.gateway.control.v1.OpenRequestResponse.decision:type_name -> sup2api.gateway.control.v1.Decision
	9,  // 5: sup2api.gateway.control.v1.OpenRequestResponse.denial:type_name -> sup2api.gateway.control.v1.Denial
	10, // 6: sup2api.gateway.control.v1.OpenRequestResponse.lease:type_name -> sup2api.gateway.control.v1.RequestLease
	11, // 7: sup2api.gateway.control.v1.OpenRequestResponse.plan:type_name -> sup2api.gateway.control.v1.ExecutionPlan
	25, // 8: sup2api.gateway.control.v1.ExecutionPlan.upstream_headers:type_name -> sup2api.gateway.control.v1.ExecutionPlan.UpstreamHeadersEntry
	26, // 9: sup2api.gateway.control.v1.ExecutionPlan.protocol_options:type_name -> sup2api.gateway.control.v1.ExecutionPlan.ProtocolOptionsEntry
	14, // 10: sup2api.gateway.control.v1.ExecutionPlan.tls_fingerprint:type_name -> sup2api.gateway.control.v1.TLSFingerprintProfile
	27, // 11: sup2api.gateway.control.v1.SignBedrockRequestRequest.headers:type_name -> sup2api.gateway.control.v1.SignBedrockRequestRequest.HeadersEntry
	1,  // 12: sup2api.gateway.control.v1.SignBedrockRequestResponse.decision:type_name -> sup2api.gateway.control.v1.Decision
	9,  // 13: sup2api.gateway.control.v1.SignBedrockRequestResponse.denial:type_name -> sup2api.gateway.control.v1.Denial
	28, // 14: sup2api.gateway.control.v1.SignBedrockRequestResponse.signed_headers:type_name -> sup2api.gateway.control.v1.SignBedrockRequestResponse.SignedHeadersEntry
	20, // 15: sup2api.gateway.control.v1.SettleRequestRequest.usage:type_name -> sup2api.gateway.control.v1.Usage
	21, // 16: sup2api.gateway.control.v1.SettleRequestRequest.upstream:type_name -> sup2api.gateway.control.v1.UpstreamResult
	2,  // 17: sup2api.gateway.control.v1.InvalidationEvent.kind:type_name -> sup2api.gateway.control.v1.InvalidationKind
	3,  // 18: sup2api.gateway.control.v1.DataPlaneControl.ResolveAPIKey:input_type -> sup2api.gateway.control.v1.ResolveAPIKeyRequest
	4,  // 19: sup2api.gateway.control.v1.DataPlaneControl.RenewAuthGrant:input_type -> sup2api.gateway.control.v1.RenewAuthGrantRequest
	7,  // 20: sup2api.gateway.control.v1.DataPlaneControl.OpenRequest:input_type -> sup2api.gateway.control.v1.OpenRequestRequest
	12, // 21: sup2api.gateway.control.v1.DataPlaneControl.SignBedrockRequest:input_type -> sup2api.gateway.control.v1.SignBedrockRequestRequest
	15, // 22: sup2api.gateway.control.v1.DataPlaneControl.RenewLease:input_type -> sup2api.gateway.control.v1.RenewLeaseRequest
	17, // 23: sup2api.gateway.control.v1.DataPlaneControl.AbortRequest:input_type -> sup2api.gateway.control.v1.AbortRequestRequest
	19, // 24: sup2api.gateway.control.v1.DataPlaneControl.SettleRequest:input_type -> sup2api.gateway.control.v1.SettleRequestRequest
	23, // 25: sup2api.gateway.control.v1.DataPlaneControl.WatchInvalidations:input_type -> sup2api.gateway.control.v1.WatchInvalidationsRequest
	5,  // 26: sup2api.gateway.control.v1.DataPlaneControl.ResolveAPIKey:output_type -> sup2api.gateway.control.v1.ResolveAPIKeyResponse
	5,  // 27: sup2api.gateway.control.v1.DataPlaneControl.RenewAuthGrant:output_type -> sup2api.gateway.control.v1.ResolveAPIKeyResponse
	8,  // 28: sup2api.gateway.control.v1.DataPlaneControl.OpenRequest:output_type -> sup2api.gateway.control.v1.OpenRequestResponse
	13, // 29: sup2api.gateway.control.v1.DataPlaneControl.SignBedrockRequest:output_type -> sup2api.gateway.control.v1.SignBedrockRequestResponse
	16, // 30: sup2api.gateway.control.v1.DataPlaneControl.RenewLease:output_type -> sup2api.gateway.control.v1.RenewLeaseResponse
	18, // 31: sup2api.gateway.control.v1.DataPlaneControl.AbortRequest:output_type -> sup2api.gateway.control.v1.AbortRequestResponse
	22, // 32: sup2api.gateway.control.v1.DataPlaneControl.SettleRequest:output_type -> sup2api.gateway.control.v1.SettleRequestResponse
	24, // 33: sup2api.gateway.control.v1.DataPlaneControl.WatchInvalidations:output_type -> sup2api.gateway.control.v1.InvalidationEvent
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_control_v1_control_proto_init() }
func file_api_control_v1_control_proto_init() {
	if File_api_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_v1_control_proto_rawDesc), len(file_api_control_v1_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_v1_control_proto_goTypes,
		DependencyIndexes: file_api_control_v1_control_proto_depIdxs,
		EnumInfos:         file_api_control_v1_control_proto_enumTypes,
		MessageInfos:      file_api_control_v1_control_proto_msgTypes,
	}.Build()
	File_api_control_v1_control_proto = out.File
	file_api_control_v1_control_proto_goTypes = nil
	file_api_control_v1_control_proto_depIdxs = nil
}
